### ISSUE TITLE
Help me to collect C++ programming basic codes.

### ISSUE THREAD

**Issue by AnujitSingh** [AnujitSingh/Code-with-CPP#2]
Add beginner cpp programs.

**Comment by sona-123** [comment]
@AnujitSingh Please assign this issue to me to work under Hacktoberfest2022. I have some basic codes.

**Comment by AnujitSingh** [comment]
> @AnujitSingh Please assign this issue to me to work under Hacktoberfest2022. I have some basic codes.

@sona-123 Hi there ☺️, you can do it by adding the file to this repository.

**Comment by Vaishnavi-More** [comment]
Hi there, please assign this issue to me.

**Comment by ashish5433** [comment]
hii @AnujitSingh pls assign this to me

**Comment by thesuaveguy** [comment]
hi @AnujitSingh ,could you please assign me this issue

**Comment by ipratham101** [comment]
hey can you please assign this to me for hacktoberfest2022
